import pandas as pd
import os

new_contacts = [
    {"Full Name": "", "Company Name": "TURN KEY UTILITY CONSTRUCTION, INC.", "Address": "9716 LIMESTONE COURT, JOSHUA, TX 76058", "Phone Number": "(817)309-3702", "Fax Number": "", "Email Address": "BOBI@TURNKEYTEXAS.NET", "Services": ""},
    {"Full Name": "", "Company Name": "TWELVE STARS CONSTRUCTION COMPANY LLC", "Address": "600 CENTER AVE. #1883, BROWNWOOD, TX 768010000", "Phone Number": "3253054497", "Fax Number": "", "Email Address": "", "Services": ""},
    {"Full Name": "", "Company Name": "U.S. TRAFFIC CONTROL, LLC", "Address": "573 HAWTHORNE AVE, ATHENS, GA 306060000", "Phone Number": "(706)369-5300", "Fax Number": "", "Email Address": "LESLY.AGENT-CRUZ@ULM.COM", "Services": ""},
    {"Full Name": "", "Company Name": "UNITED CLEANING SERVICE INC.", "Address": "17423 WILD WILLOW LANE, HOUSTON, TX 77084", "Phone Number": "(832)782-2932", "Fax Number": "", "Email Address": "SANTOSERIVAS@OUTLOOK.COM", "Services": ""},
    {"Full Name": "", "Company Name": "URETEK USA, INC.", "Address": "PO BOX 1929, TOMBALL, TX 773770000", "Phone Number": "2813517800", "Fax Number": "", "Email Address": "EHIBBARD@URETEKUSA.COM", "Services": ""},
    {"Full Name": "", "Company Name": "USA AMTECH, INC.", "Address": "PO BOX 507, THE WOODLANDS, TX 773820000", "Phone Number": "(469)972-7956", "Fax Number": "", "Email Address": "MOHSIN@USAMTECH.COM", "Services": ""},
    {"Full Name": "", "Company Name": "USA DT SERVICES, INC.", "Address": "12650 W. 64TH AVE. UNIT 504, ARVADA, CO 800040000", "Phone Number": "(701)570-1433", "Fax Number": "", "Email Address": "OWEN.SMITH@DTSERVICES.COM", "Services": ""},
    {"Full Name": "", "Company Name": "V & F MAINTENANCE, LLC.", "Address": "363 WILLOW GROVE, WACO, TX 76712", "Phone Number": "(254)366-9999", "Fax Number": "", "Email Address": "VFMAINTENANCE@YAHOO.COM", "Services": ""},
    {"Full Name": "", "Company Name": "V. K. KNOWLTON CONSTRUCTION AND UTILITIES, INC.", "Address": "18225 FM 2252, SAN ANTONIO, TX 782660000", "Phone Number": "2106516860", "Fax Number": "", "Email Address": "STEVEN@VKK.COM", "Services": ""},
    {"Full Name": "Valentine Nwankwo", "Company Name": "CHIVALRY CAPITAL PARTNERS LLC", "Address": "19414 Curly Mesquite Dr, Cypress, TX 77433", "Phone Number": "469-233-3758", "Fax Number": "", "Email Address": "vnwankwo@chivalrycp.com", "Services": "Project Management & Business Management Consulting Services; Procurement of Equipment Pipe Fabrication & Engineering Consulting"},
    {"Full Name": "Valerie Leist", "Company Name": "HILL COUNTRY BRIDGE, INC.", "Address": "10001 Hwy 46, New Braunfels, TX 78132", "Phone Number": "830-885-4294", "Fax Number": "", "Email Address": "vleist@hillcountrybridge.com", "Services": "Highway, Street, & Bridge Construction; Drainage project construction; Highway bridge sections, prefabricated metal, manufacturing; Concrete finishing; Poured Concrete Foundation and Structure Contractors; Concrete paving (i.e., highway, road, street, public sidewalk)"},
    {"Full Name": "Valerie Moore", "Company Name": "MINORITY WOMAN CONSTRUCTION", "Address": "219 Weatherly Way, Houston, TX 77022", "Phone Number": "281-716-0203", "Fax Number": "", "Email Address": "minoritywomanconstruction@yahoo.com", "Services": "Concrete Work i.e. Sidewalks, Patios, and Driveways/Flagman Services/Project Management for Waterline Replacement/Install Pipe for Underground Utilities/Water Pipes (Residential)/Piping Supplier"},
    {"Full Name": "", "Company Name": "VALOR GC", "Address": "1337 JIM PAUL, EL PASO, TX 799360000", "Phone Number": "9157406017", "Fax Number": "", "Email Address": "GCEPEDA@VALOR-GC.COM", "Services": ""},
    {"Full Name": "", "Company Name": "VALUE DRILLING COMPANY INC", "Address": "4102 ALDINE MAIL RT ROAD, HOUSTON, TX 770390000", "Phone Number": "7134740119", "Fax Number": "", "Email Address": "SIDDIQUE@VALUEDRILLING.COM", "Services": ""},
    {"Full Name": "Vandana Gopalan", "Company Name": "THE BARGAIN SOURCE", "Address": "2516 Morningside Drive, Garland, TX 75041", "Phone Number": "972-278-2635", "Fax Number": "", "Email Address": "gctbs@prodigy.net", "Services": "Wholesaler of Bulk Fragrances and Chemical Dyes; Drugs and Druggists' Sundries Merchant Wholesalers; Supply Purchase and Delivery"},
    {"Full Name": "Vanessa Halsey", "Company Name": "THE ASHELYN GROUP, LLC", "Address": "615 Abrams St, Suite D, Arlington, TX 76010", "Phone Number": "817-907-1613", "Fax Number": "", "Email Address": "marcocorptx@gmail.com", "Services": "Construction management, highway, road, street and bridge; Project Management; Miscellaneous - Design/Build & Facilities Management"},
    {"Full Name": "", "Company Name": "VANN/ELLI, INC.", "Address": "PO BOX 1060, JOSHUA, TX 760580000", "Phone Number": "8175584052", "Fax Number": "(817)645-5352", "Email Address": "VANN1ELLI@AOL.COM", "Services": ""},
    {"Full Name": "", "Company Name": "VAULT MOBILE STORAGE LLC", "Address": "415 W WALL STREET SUITE 326, MIDLAND, TX 79701", "Phone Number": "(432)559-3025", "Fax Number": "", "Email Address": "", "Services": ""},
    {"Full Name": "", "Company Name": "VECTOR FORCE DEVELOPMENT, LLC", "Address": "1606 EASTPORT PLAZA DR., COLLINSVILLE, IL 62234", "Phone Number": "(855)729-7448", "Fax Number": "", "Email Address": "BIDS@VECTORSERVICESUS.COM", "Services": ""},
    {"Full Name": "", "Company Name": "VEMAC, LLC", "Address": "1919 E RIO GRANDE, EL PASO, TX 799020000", "Phone Number": "9155661911", "Fax Number": "", "Email Address": "LESTALA@VEMAC.US", "Services": ""},
    {"Full Name": "", "Company Name": "VERNARA LLC", "Address": "11816 INWOOD RD 1105, DALLAS, TX 752440000", "Phone Number": "3057609005", "Fax Number": "", "Email Address": "ASHKAN@VERNARA.COM", "Services": ""},
    {"Full Name": "Veronica Macias", "Company Name": "EL ROI CONSTRUCTION, INC.", "Address": "3110 Trawood Drive, Suite B, El Paso, TX 79936", "Phone Number": "915-333-2613", "Fax Number": "", "Email Address": "elroiconstruction@yahoo.com", "Services": "Poured Concrete Foundation and Structure Contractors; Concrete breaking and cutting for demolition; Landscaping Services; Concrete Paving and Incidentals - includes jointed concrete pavement and continuously reinforced concrete pavement; Earthwork, Base and Subbase - includes preparing ROW, clearing, removing old concrete, roadway and channel excavation, embankments, subbase courses, base courses, etc.; Landscaping - includes roadside planting, erosion control, sodding, seeding, etc."},
    {"Full Name": "Veronica Mahan", "Company Name": "MAHAN CONSTRUCTION CONSULTANTS", "Address": "204 South Brownson St., Victoria, TX 77901", "Phone Number": "361-687-3901", "Fax Number": "", "Email Address": "mahanconstruction@outlook.com", "Services": "Construction consulting and management"},
    {"Full Name": "", "Company Name": "VERSABUCKET, LLC", "Address": "15720 GARRETT RD, HOUSTON, TX 770440000", "Phone Number": "8327773001", "Fax Number": "", "Email Address": "NROBERTS@VERSABUCKET.COM", "Services": ""},
    {"Full Name": "", "Company Name": "VERSARE MANAGEMENT, LLC", "Address": "P.O. BOX 270474, HOUSTON, TX 772770000", "Phone Number": "(832)757-8240", "Fax Number": "", "Email Address": "AM@VERSAREMGMT.COM", "Services": ""},
    {"Full Name": "", "Company Name": "VERTICAL TRACTOR MOWING, LLC", "Address": "4180 N SMITH ROAD, ROCKWALL, TX 75087", "Phone Number": "(972)922-3333", "Fax Number": "", "Email Address": "MICHELLE@VERTICALTRACTOR.NET", "Services": ""},
    {"Full Name": "Vicki Helm", "Company Name": "LONE STAR GRADING & MATERIALS, LLC", "Address": "6571 Elm Grove Rd, Belton, TX 76513", "Phone Number": "254-947-0149", "Fax Number": "", "Email Address": "vicki.helm@lonestargrading.com", "Services": "Highway Construction, Hauling, Concrete paving, Excavation; Asphalt paving; Concrete finishing; Excavating, earthmoving, or land clearing contractors"},
    {"Full Name": "Vicki Helm", "Company Name": "LONE STAR GRADING & MATERIALS, LTD.", "Address": "6571 Elm Grove Rd, Belton, TX 76513", "Phone Number": "254-947-0149", "Fax Number": "", "Email Address": "vicki.helm@lonestargrading.com", "Services": "Highway Construction, Hauling, Concrete paving, Excavation; Asphalt paving; Concrete finishing; Excavating, earthmoving, or land clearing contractors"},
    {"Full Name": "Victor Ezike", "Company Name": "DACIK GLOBAL HOLDINGS, LLC", "Address": "13119 WINDMILL GROVE DR, RICHMOND, TX 77407", "Phone Number": "713-502-4435", "Fax Number": "", "Email Address": "evictore@hotmail.com", "Services": "Project management, mechanical piping construction & design consultant; Hauling services"},
    {"Full Name": "Victor F Aranda", "Company Name": "RUDD-PALMER CO., INC.", "Address": "P. O. BOX 10146, AMARILLO, TX 79116", "Phone Number": "806-374-8581", "Fax Number": "", "Email Address": "jerry@ruddpalmer.com", "Services": "Highway Construction, Concrete repair, Wood floor finishing, Waterproofing contractors, Expansion joints, metal, manufacturing"},
    {"Full Name": "", "Company Name": "VIMAS PAINTING COMPANY, INC.", "Address": "4328 MCCARTNEY RD, LOWELLVILLE, OH 444360000", "Phone Number": "3305362222", "Fax Number": "", "Email Address": "VIMAS@VIMASPAINTING.COM", "Services": ""},
    {"Full Name": "", "Company Name": "VIZCAINO, L.P.", "Address": "2210 W. 16TH STREET, ODESSA, TX 797630000", "Phone Number": "4323328433", "Fax Number": "", "Email Address": "JUAN@VIZCAINOLP.COM", "Services": "Highway, Street, and Bridge Construction"},
    {"Full Name": "", "Company Name": "VNA ROAD & BRIDGE LLC", "Address": "PO BOX 71597, EL PASO, TX 79917", "Phone Number": "(915)777-0335", "Fax Number": "", "Email Address": "JANGUIANO@VNAROAD.COM", "Services": ""},
    {"Full Name": "", "Company Name": "VSS INTERNATIONAL, INC.", "Address": "3785 CHANNEL DRIVE, WEST SACRAMENTO, CA 95691", "Phone Number": "9163731500", "Fax Number": "", "Email Address": "VSSIESTIMATING@SLURRY.COM", "Services": ""},
    {"Full Name": "", "Company Name": "VULCAN MATERIALS ASPHALT AND CONSTRUCTION, LLC", "Address": "1575 FM 1485, CONROE, TX 773010000", "Phone Number": "9367566960", "Fax Number": "", "Email Address": "TXDOTBIDSVMAC@VMCMAIL.COM", "Services": ""},
    {"Full Name": "", "Company Name": "W. M. MILLER CONSTRUCTION COMPANY, INC.", "Address": "PO BOX 38, JUDSON, TX 756600000", "Phone Number": "9036634172", "Fax Number": "", "Email Address": "THERESA@MILLERCCI.COM", "Services": ""},
    {"Full Name": "", "Company Name": "WASTE SOLUTIONS USA LLC", "Address": "28664 KYLE ROAD, WALLER, TX 77484", "Phone Number": "(832)405-6296", "Fax Number": "", "Email Address": "FABRICIO@WASTESOLUTIONSUSA.COM", "Services": ""},
    {"Full Name": "Watts Long", "Company Name": "WATTS LONG EXPRESS", "Address": "1620 WILSON AVE, WACO, TX 76708", "Phone Number": "254-716-2248", "Fax Number": "", "Email Address": "wattslong9@aol.com", "Services": "Hauling"},
    {"Full Name": "Waylon Boyles", "Company Name": "", "Address": "3280 DEAD MAN RD, HUNTINGTON, TX 759490000", "Phone Number": "9366765276", "Fax Number": "", "Email Address": "WBOYLES@VECTORCONTRACTING.COM", "Services": ""},
    {"Full Name": "Wayne Boyter", "Company Name": "ACUMEN ENTERPRISES, INC.", "Address": "1504 Falcon Drive, DeSoto, TX 75115", "Phone Number": "972-572-0701", "Fax Number": "", "Email Address": "wayne@acumen-enterprises.com", "Services": "General Construction and Contract Services Provider"},
    {"Full Name": "", "Company Name": "WAYNE YANCEY, INC.", "Address": "P.O. BOX 1244, MAGNOLIA, TX 773530000", "Phone Number": "(281)830-5113", "Fax Number": "", "Email Address": "TLYANCEY20@GMAIL.COM", "Services": ""},
    {"Full Name": "", "Company Name": "WE BUILD, INC.", "Address": "PO BOX 876, PARIS, TX 754600000", "Phone Number": "(903)783-3684", "Fax Number": "(903)783-1722", "Email Address": "RGARCIA@HWH1887.COM", "Services": ""},
    {"Full Name": "", "Company Name": "WE PAVE ROAD CONSTRUCTION L.L.C.", "Address": "2801 RICHMOND ROAD # 213, TEXARKANA, TX 75503", "Phone Number": "(903)556-0967", "Fax Number": "", "Email Address": "WEPAVEROAD@GMAIL.COM", "Services": ""},
    {"Full Name": "", "Company Name": "WEBBER INFRASTRUCTURE MANAGEMENT, INC.", "Address": "10415 MORADO CIRCLE BLDG.2 SUITE 200, AUSTIN, TX 787590000", "Phone Number": "7139642800", "Fax Number": "", "Email Address": "BIDDING.INFRA@WWEBBER.COM", "Services": ""},
    {"Full Name": "", "Company Name": "WEBBER WATERWORKS, LLC", "Address": "1725 HUGHES LANDING BLVD. STE 1200, THE WOODLANDS, TX 773800000", "Phone Number": "2819078600", "Fax Number": "", "Email Address": "BIDS@PLWUS.COM", "Services": ""},
    {"Full Name": "", "Company Name": "WEBBER, LLC", "Address": "1725 HUGHES LANDING BLVD STE 1200, THE WOODLANDS, TX 773800000", "Phone Number": "2819078600", "Fax Number": "(281)449-6658", "Email Address": "WEBBERESTIMATING@WWEBBER.COM", "Services": ""},
    {"Full Name": "", "Company Name": "WEEKS MARINE, INC.", "Address": "4 COMMERCE DRIVE, CRANFORD, NJ 70160000", "Phone Number": "9082724010", "Fax Number": "(908)272-4740", "Email Address": "TRINA.SABATKA@KIEWIT.COM", "Services": ""},
    {"Full Name": "", "Company Name": "WELLCRAFT BUILDERS", "Address": "16756 MARSALA SPRINGS DR, ROUND ROCK, TX 786810000", "Phone Number": "2155547834", "Fax Number": "", "Email Address": "VARUN@WELLCRAFTBUILDERS.COM", "Services": ""},
    {"Full Name": "", "Company Name": "WELLMANN ENTERPRISES", "Address": "PO BOX 1003, BRENHAM, TX 778340000", "Phone Number": "9798303898", "Fax Number": "", "Email Address": "RLWELLMANN@YAHOO.COM", "Services": ""},
    {"Full Name": "Wendell Robbins", "Company Name": "W. A. ROBBINS CONSTRUCTION CO., INC.", "Address": "4622 Dagg Road, Houston, TX 77048", "Phone Number": "713-644-5823", "Fax Number": "", "Email Address": "wendell3@warobbinsconstruction.com", "Services": "Interior & Exterior Renovations, Concrete Construction, and Underground Utilities (cabling & fiber optics)"},
    {"Full Name": "Wendell Wilson", "Company Name": "WILSON BUILDING SERVICES, INC.", "Address": "13955 Murphy Road, Suite 124, Stafford, TX 77477", "Phone Number": "281-780-0700", "Fax Number": "", "Email Address": "info@wilsonbuildingservice.com", "Services": "Home Owner Association Services and Repairs; Pressure Washing, window Washing, Project Mgmt, and Seasonal Decorations, Painting, Sheet Rock Installation, and Driveway Paving Only"},
    {"Full Name": "", "Company Name": "WEST TEXAS PAVING, INC.", "Address": "10104 ALCOVE AVE, WOLFFORTH, TX 793820000", "Phone Number": "8068332882", "Fax Number": "(806)863-3550", "Email Address": "", "Services": ""},
    {"Full Name": "", "Company Name": "WEST TEXAS ROCK RESOURCES, LLC", "Address": "P.O. BOX 871, ROSCOE, TX 795450000", "Phone Number": "3257663033", "Fax Number": "", "Email Address": "", "Services": ""},
    {"Full Name": "", "Company Name": "WILLIAM CHARLES CONSTRUCTION COMPANY, LLC", "Address": "PO BOX 2071, LOVES PARK, IL 61130", "Phone Number": "(815)654-4700", "Fax Number": "", "Email Address": "NATALIE.LATINO@WILLIAMCHARLES.COM", "Services": ""},
    {"Full Name": "", "Company Name": "WILLIAMS BROTHERS CONSTRUCTION CO., INC.", "Address": "PO BOX 66428, HOUSTON, TX 772660000", "Phone Number": "7135229821", "Fax Number": "(713)520-5247", "Email Address": "BLANHAM@WBCTX.COM", "Services": ""},
    {"Full Name": "Willie Singleton", "Company Name": "INDUSTRIAL CONSTRUCTION CO.", "Address": "121 Springtree Grove, Cibolo, TX 78108", "Phone Number": "210-859-6042", "Fax Number": "", "Email Address": "indconst019@gmail.com", "Services": "Highway, Street, and Bridge Construction, Foundation, building, poured concrete, contractors, All Other Specialty Trade Contractors, Administrative Management and General Management Consulting Services"},
    {"Full Name": "", "Company Name": "WILLIS ELECTRIC CO., LP", "Address": "PO BOX 7109, ABILENE, TX 796080000", "Phone Number": "3256983444", "Fax Number": "(325)698-3446", "Email Address": "tommy@willislp.com", "Services": "Underground Utility, Illumination, Traffic Control Devices Miscellaneous: Small Highway Signs"},
    {"Full Name": "", "Company Name": "WILSONS FLAGGING CONTROL COMPANY LLC", "Address": "403 RICHARDSON RD. E, LIVINGSTON, TX 77351", "Phone Number": "8328779352", "Fax Number": "", "Email Address": "ALANW716@GMAIL.COM", "Services": ""},
    {"Full Name": "", "Company Name": "WINDING ROAD CONSTRUCTION, INC.", "Address": "39036 COUNTY ROAD 225, BIGFORK, MN 566280000", "Phone Number": "2187431877", "Fax Number": "(218)743-6048", "Email Address": "WINDINGROAD1877@YAHOO.COM", "Services": ""},
    {"Full Name": "", "Company Name": "W-INDUSTRIES OF TEXAS, LLC", "Address": "8303 THORA LN, SPRING, TX 77379", "Phone Number": "(713)466-9463", "Fax Number": "", "Email Address": "GUY_GOODSPEED@W-INDUSTRIES.COM", "Services": ""},
    {"Full Name": "", "Company Name": "WITHERS CONSTRUCTION, LLC", "Address": "1202 COUNTY ROAD 44850, BLOSSOM, TX 754160000", "Phone Number": "9039053385", "Fax Number": "", "Email Address": "WITHERSCONSTRUCTION@YAHOO.COM", "Services": ""},
    {"Full Name": "", "Company Name": "WMS R AND B, L.L.C.", "Address": "P.O. BOX 1869, MARSHALL, TX 75671", "Phone Number": "(903)754-0882", "Fax Number": "", "Email Address": "WMS@WMSRANDB.COM", "Services": ""},
    {"Full Name": "", "Company Name": "WRIGHT BROTHERS CONSTRUCTION COMPANY, INC.", "Address": "PO BOX 437, CHARLESTON, TN 373100000", "Phone Number": "4233362261", "Fax Number": "", "Email Address": "BBREWER@WBCCI.COM", "Services": ""},
    {"Full Name": "", "Company Name": "W-TEX SERVICES LLC", "Address": "480 MILL OAK LN, SEGUIN, TX 781550000", "Phone Number": "8303212276", "Fax Number": "", "Email Address": "W-TEX@OUTLOOK.COM", "Services": ""},
    {"Full Name": "", "Company Name": "XIT PAVING AND CONSTRUCTION INC.", "Address": "3934 S. HWY 287, WAXAHACHIE, TX 751650000", "Phone Number": "(972)351-9906", "Fax Number": "(972)289-3249", "Email Address": "ESTIMATING@XITPAVING.COM", "Services": ""},
    {"Full Name": "", "Company Name": "XTREME PRO CLEANING LLC", "Address": "10501 FOY LANE, HOUSTON, TX 770930000", "Phone Number": "7133843117", "Fax Number": "", "Email Address": "ANGELA6595@AOL.COM", "Services": ""},
    {"Full Name": "Yahir Alcantana", "Company Name": "RANCHO CONSTRUCTION LLC", "Address": "563 AVENUE D, LAKEHILLS, TX 78063", "Phone Number": "210-992-2704", "Fax Number": "", "Email Address": "info@rancho-construction.com", "Services": "Janitorial services, guardrails, mowing, tree removal, landscaping, pressure washing"},
    {"Full Name": "Yara Corbitt", "Company Name": "TEXAS CORDIA CONSTRUCTION, LLC", "Address": "3149A Center Pointe Drive, Edinburg, TX 78539", "Phone Number": "956-627-6181", "Fax Number": "", "Email Address": "yara@texascordia.com", "Services": "Asphalt paving (i.e., highway, road, street, public sidewalk); Highway construction; Asphalt - includes seal coats and surface treatments, limestone rock asphalt, cold-mix asphaltic concrete pavement, hot mix asphaltic concrete pavement, etc.; Major Structures - includes structural excavation, drill shafts, piling, concrete for columns, bents, abutments, slabs, structural steel, rebar, etc."},
    {"Full Name": "", "Company Name": "YELLABUSH CONSTRUCTION SERVICES, LLC", "Address": "PO BOX 10653, LUBBOCK, TX 79416", "Phone Number": "(806)577-4538", "Fax Number": "", "Email Address": "AARON@YB-ENERGY.COM", "Services": ""},
    {"Full Name": "", "Company Name": "YELLOWSTONE LANDSCAPE - CENTRAL, INC.", "Address": "10892 SHADOW WOOD DRIVE, HOUSTON, TX 770430000", "Phone Number": "7134628552", "Fax Number": "", "Email Address": "JRICHARDSON@YELLOWSTONELANDSCAPE.COM", "Services": ""},
    {"Full Name": "Yolanda Diaz", "Company Name": "MIRADOR ENTERPRISES, INC.", "Address": "8201 Lockheed Dr., Ste. 110, El Paso, TX 79925", "Phone Number": "915-546-4111", "Fax Number": "(915)351-7903", "Email Address": "ydiaz@miradorenterprises.com", "Services": "Facilities support services in maintenance and management services, Janitorial services including commercial maintenance and repairs; Commercial and Institutional Building Construction; Highway, Street, and Bridge Construction"},
    {"Full Name": "", "Company Name": "YUNEX LLC", "Address": "9225 BEE CAVE ROAD BLDG B, SUITE 201, AUSTIN, TX 787330000", "Phone Number": "(714)497-5043", "Fax Number": "", "Email Address": "ESTIMATINGTX@YUNEXTRAFFIC.COM", "Services": ""},
    {"Full Name": "Yvette Robinson", "Company Name": "ROBINSON GENERAL CONTRACTORS, LLC", "Address": "20770 US 281N #108-288, San Antonio, TX 78258", "Phone Number": "210-303-3733", "Fax Number": "", "Email Address": "yrobinson@robinsongc.com", "Services": "Construction management, commercial and institutional building, Concrete paving (i.e., highway, road, street, public sidewalk), Concrete pouring, Fencing contractors (except electronic containment fencing for pets)"},
    {"Full Name": "", "Company Name": "Z3 WELDING GONZALES LLC", "Address": "1307 E 3RD ST ST B, BIG SPRING, TX 79720", "Phone Number": "(432)517-7073", "Fax Number": "", "Email Address": "AGONZALES509@GMAIL.COM", "Services": ""},
    {"Full Name": "", "Company Name": "ZACHRY CONSTRUCTION CORPORATION", "Address": "PO BOX 33240, SAN ANTONIO, TX 782650000", "Phone Number": "2108712700", "Fax Number": "(210)871-6906", "Email Address": "JIM.AUSTIN@ZACHRYCORP.COM", "Services": ""},
    {"Full Name": "", "Company Name": "ZACK BURKETT CO.", "Address": "PO BOX 40, GRAHAM, TX 764500000", "Phone Number": "9405490436", "Fax Number": "(940)549-4565", "Email Address": "ZT@ZACKBURKETTCO.COM", "Services": ""},
    {"Full Name": "", "Company Name": "ZEBRA PARKING LOT STRIPING & RESTORATIONS, LLC", "Address": "315 PEAR RD, GLADEWATER, TX 75647", "Phone Number": "(903)401-7743", "Fax Number": "", "Email Address": "ZEBRALOT@GMAIL.COM", "Services": ""}
]

# Convert to DataFrame
df_new = pd.DataFrame(new_contacts)

csv_file = "houston_construction_leads.csv"

if os.path.isfile(csv_file):
    df_new.to_csv(csv_file, mode='a', header=False, index=False)
    print(f"✅ Appended {len(df_new)} leads to '{csv_file}'")
else:
    df_new.to_csv(csv_file, index=False)
    print(f"✅ Created '{csv_file}' with {len(df_new)} leads")